CREATE TABLE place_features (
    id SERIAL PRIMARY KEY,
    place TEXT,

    avg_cost_per_day FLOAT,
    trip_duration FLOAT,

    popularity_high SMALLINT,
    popularity_medium SMALLINT,
    popularity_offbeat SMALLINT,
    popularity_very_high SMALLINT,

    adventure SMALLINT,
    beach SMALLINT,
    bird_watching SMALLINT,
    boating SMALLINT,
    camping SMALLINT,
    canyon SMALLINT,
    caves SMALLINT,
    culture SMALLINT,
    desert SMALLINT,
    food SMALLINT,
    forest SMALLINT,
    heritage SMALLINT,
    history SMALLINT,
    islands SMALLINT,
    lakes SMALLINT,
    luxury SMALLINT,
    mountains SMALLINT,
    nature SMALLINT,
    nightlife SMALLINT,
    offbeat SMALLINT,
    paragliding SMALLINT,
    peaceful SMALLINT,
    rafting SMALLINT,
    river SMALLINT,
    romantic SMALLINT,
    safari SMALLINT,
    skiing SMALLINT,
    spiritual SMALLINT,
    trekking SMALLINT,
    water_sports SMALLINT,
    waterfalls SMALLINT,

    apr SMALLINT,
    aug SMALLINT,
    dec SMALLINT,
    feb SMALLINT,
    jan SMALLINT,
    jul SMALLINT,
    jun SMALLINT,
    mar SMALLINT,
    may SMALLINT,
    nov SMALLINT,
    oct SMALLINT,
    sep SMALLINT,

    couple SMALLINT,
    family SMALLINT,
    friends SMALLINT,
    solo SMALLINT,

    total_cost_log FLOAT,

    region_africa SMALLINT,
    region_europe SMALLINT,
    region_middle_east SMALLINT,
    region_north_america SMALLINT,
    region_oceania SMALLINT,
    region_south_asia SMALLINT,
    region_southeast_asia SMALLINT,
    region_nan SMALLINT,

    climate_alpine SMALLINT,
    climate_cold SMALLINT,
    climate_continental SMALLINT,
    climate_dry SMALLINT,
    climate_highland SMALLINT,
    climate_mediterranean SMALLINT,
    climate_subtropical SMALLINT,
    climate_temperate SMALLINT,
    climate_tropical SMALLINT,
    climate_nan SMALLINT
);
