const API_BASE = "http://127.0.0.1:5000";
let joinMode = false; // true when user joins an existing trip (skip role step)

/* ---------- PAGE NAVIGATION ---------- */
function go(screenId) {
  document.querySelectorAll(".screen").forEach(s => s.classList.remove("active"));
  document.getElementById(screenId).classList.add("active");
}

function startCreateFlow() {
  joinMode = false;
  document.getElementById("userNameInput").value = "";
  document.getElementById("nameError").style.display = "none";
  go("username");
}

async function proceedAfterRole() {
  const roleCard = document.querySelector("#role .card.selected");
  if (!roleCard) {
    alert("Please select a travel type");
    return;
  }
  
  const roleText = roleCard.innerText.split(" ")[1].toLowerCase();
  
  // Only create group for group modes (friends, couples, family)
  if (!joinMode && roleText !== "solo") {
    // Create group for team owner
    try {
      console.log("Creating group...");
      const res = await fetch(`${API_BASE}/create_group`, { method: "GET" });
      const data = await res.json();
      console.log("Group created:", data);
      localStorage.setItem("currentGroup", data.group_id);
      localStorage.setItem("isGroupOwner", "true");
      go("interests");
    } catch (err) {
      console.error("Error creating group:", err);
      alert("Failed to create group: " + err.message);
    }
  } else {
    // Solo travelers or joiners proceed directly to interests
    console.log("Proceeding to interests (solo or join mode)");
    go("interests");
  }
}

function showLobby() {
  go("group");
  const groupId = localStorage.getItem("currentGroup");
  const currentUserName = localStorage.getItem("currentUserName") || "Anonymous";
  
  // Display team code
  document.getElementById("groupTeamCode").innerText = groupId;
  
  // Add current user to group and fetch members
  addCurrentUserToGroup(groupId, currentUserName);
  
  // Start polling to refresh member list every 2 seconds
  const lobbyRefreshInterval = setInterval(() => {
    if (document.querySelector(".screen.active")?.id === "group") {
      fetchAndRenderMembers(groupId, currentUserName);
    } else {
      clearInterval(lobbyRefreshInterval);
    }
  }, 2000);
  localStorage.setItem("lobbyRefreshInterval", lobbyRefreshInterval);
}

function proceedToBudget() {
  // 1. FIX: Check joinMode first. If they joined a team, they MUST go to lobby.
  if (joinMode) {
    showLobby();
    return;
  }

  // Check if user is solo (for creators)
  const roleCard = document.querySelector("#role .card.selected");
  const roleText = roleCard
    ? roleCard.innerText.split(" ")[1].toLowerCase()
    : "solo";

  if (roleText === "solo") {
    runRecommendationFlow();
  } else {
    showLobby();
  }
}

async function addCurrentUserToGroup(groupId, currentUserName) {
  const roleCard = document.querySelector("#role .card.selected");
  const user_type = roleCard
    ? roleCard.innerText.split(" ")[1].toLowerCase()
    : "solo";

  const selectedChips = document.querySelectorAll(".chip.selected");
  const user_interests = Array.from(selectedChips).map(c => (c.dataset.tag || "").toLowerCase());

  const budgetCard = document.querySelector("#budget .card.selected");
  let budgetText = budgetCard ? budgetCard.innerText.trim() : "Low";
  const user_budget = budgetText.includes("Low")
    ? "low"
    : budgetText.includes("Medium")
    ? "mid"
    : "high";

  try {
    console.log("Adding user to group...", { groupId, currentUserName, user_type, user_interests, user_budget });
    const res = await fetch(`${API_BASE}/join_group`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        group_id: groupId,
        user_name: currentUserName,
        user_type: user_type,
        user_interests: user_interests,
        user_budget: user_budget
      })
    });

    if (res.ok) {
      console.log("User added to group");
      // Now fetch all members
      fetchAndRenderMembers(groupId, currentUserName);
    } else {
      const errorData = await res.json().catch(() => ({}));
      console.error("Failed to add user to group:", res.status, errorData);
      alert("Error: " + (errorData.error || "Failed to join group"));
    }
  } catch (err) {
    console.error("Error adding user to group:", err);
    alert("Error: " + err.message);
  }
}

async function fetchAndRenderMembers(groupId, currentUserName) {
  try {
    const res = await fetch(`${API_BASE}/get_group_members`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ group_id: groupId })
    });

    if (res.ok) {
      const data = await res.json();
      renderMembers(data.members, currentUserName);

      // 2. FIX: Check if the trip has already been generated by the host
      if (data.trip_results && data.trip_results.length > 0) {
        // Stop polling
        const intervalId = localStorage.getItem("lobbyRefreshInterval");
        if (intervalId) clearInterval(intervalId);
        
        // Show results to this user
        console.log("Trip generated! Syncing results...");
        renderResults(data.trip_results);
        go("results");
      }

    } else {
      console.error("Failed to fetch members");
    }
  } catch (err) {
    console.error("Failed to fetch members:", err);
  }
}
function renderMembers(members, currentUserName) {
  const container = document.getElementById("membersList");
  container.innerHTML = "";

  members.forEach(member => {
    const card = document.createElement("div");
    card.className = "member-card ready";
    
    const isCurrentUser = member.name === currentUserName;
    const badge = `<span class="status-badge ready">${isCurrentUser ? "You" : "Ready"}</span>`;
    
    const interestSummary = (member.interests || []).slice(0, 3).join(", ") || "No interests";
    
    card.innerHTML = `
      <div class="member-name">${member.name}</div>
      <div class="member-status">${member.user_type || "Traveler"}</div>
      <div style="font-size: 0.9rem; color: var(--muted); margin-top: 8px;">
        ${interestSummary}
      </div>
      ${badge}
    `;
    
    container.appendChild(card);
  });
}

function startJoinFlow() {
  joinMode = true;
  document.getElementById("teamcodeInput").value = "";
  document.getElementById("teamcodeError").style.display = "none";
  go("username");
}

/* ---------- USERNAME CAPTURE ---------- */
async function proceedWithName() {
  const name = document.getElementById("userNameInput").value.trim();
  const errorEl = document.getElementById("nameError");
  
  if (!name) {
    errorEl.textContent = "Please enter your name";
    errorEl.style.display = "block";
    return;
  }
  
  // Store name in localStorage
  localStorage.setItem("currentUserName", name);
  errorEl.style.display = "none";
  
  // Proceed based on mode
  if (joinMode) {
    go("teamcode");
  } else {
    go("role");
  }
}

async function joinTeam() {
  const teamcode = document.getElementById("teamcodeInput").value.trim().toUpperCase();
  const errorEl = document.getElementById("teamcodeError");

  if (!teamcode) {
    errorEl.textContent = "Please enter a team code";
    errorEl.style.display = "block";
    return;
  }

  // Store the team code and proceed to interests selection
  localStorage.setItem("currentGroup", teamcode);
  localStorage.setItem("isGroupOwner", "false");
  errorEl.style.display = "none";
  go("interests");
}

/* ---------- ROLE SELECTION ---------- */
function selectRole(el) {
  document.querySelectorAll("#role .card").forEach(c => c.classList.remove("selected"));
  el.classList.add("selected");
  document.getElementById("roleContinue").disabled = false;
}

/* ---------- INTEREST TAGS ---------- */
const tags = [
  "Mountains", "Beach", "Nature", "Forest", "Waterfalls",
  "Lakes", "Desert", "River", "Islands", "Caves",
  "Trekking", "Adventure", "Camping", "Safari", "Rafting",
  "Skiing", "Paragliding", "Water-sports", "Bird-watching", "Boating",
  "Heritage", "Spiritual", "Culture", "Peaceful", "Offbeat",
  "Romantic", "History", "Luxury", "Food", "Nightlife"
];

const tagIcons = {
  "Mountains": "⛰️",
  "Beach": "🏖️",
  "Nature": "🌿",
  "Forest": "🌲",
  "Waterfalls": "💧",
  "Lakes": "🏞️",
  "Desert": "🏜️",
  "River": "🌊",
  "Islands": "🏝️",
  "Caves": "🕳️",
  "Trekking": "🥾",
  "Adventure": "⚡",
  "Camping": "🏕️",
  "Safari": "🦁",
  "Rafting": "🛶",
  "Skiing": "🎿",
  "Paragliding": "🪂",
  "Water-sports": "🏄‍♂️",
  "Bird-watching": "🦜",
  "Boating": "⛵",
  "Heritage": "🏛️",
  "Spiritual": "🧘",
  "Culture": "🎭",
  "Peaceful": "🕊️",
  "Offbeat": "🌀",
  "Romantic": "❤️",
  "History": "📜",
  "Luxury": "💎",
  "Food": "🍜",
  "Nightlife": "🌃"
};

const chipContainer = document.getElementById("chipContainer");

tags.forEach(tag => {
  const chip = document.createElement("div");
  chip.className = "chip";
  const icon = tagIcons[tag] || "•";
  chip.dataset.tag = tag;
  chip.innerHTML = `${icon} <span>${tag}</span>`;
  chip.onclick = () => {
    chip.classList.toggle("selected");
    const selected = document.querySelectorAll(".chip.selected").length;
    document.getElementById("interestContinue").disabled = selected < 3;
  };
  chipContainer.appendChild(chip);
});

/* ---------- BUDGET ---------- */
function selectBudget(el) {
  document.querySelectorAll("#budget .card").forEach(c => c.classList.remove("selected"));
  el.classList.add("selected");
  document.getElementById("budgetContinue").disabled = false;
}

/* ---------- JOIN CODE ---------- */
document.getElementById("joinCode").innerText =
  "TS-" + Math.floor(Math.random() * 9000 + 1000);

/* ---------- LOADING -> RESULTS ---------- */
const loadingMessages = [
  "Balancing vibes...",
  "Resolving travel conflicts...",
  "Maximizing group happiness..."
];

let i = 0;

function startLoading() {
  go("loading");

  setInterval(() => {
    i = (i + 1) % loadingMessages.length;
    document.getElementById("loadingMessage").innerText = loadingMessages[i];
  }, 1200);

  setTimeout(() => {
    go("results");
  }, 3000);
}

/* ---------- FINAL API CALL + DISPLAY RESULTS ---------- */

async function generateRecommendations() {
  const roleCard = document.querySelector("#role .card.selected");
  const roleText = roleCard
    ? roleCard.innerText.split(" ")[1].toLowerCase()
    : "solo";

  const selectedChips = document.querySelectorAll(".chip.selected");
  const user_interests = Array.from(selectedChips).map(c => (c.dataset.tag || "").toLowerCase());

  const budgetCard = document.querySelector("#budget .card.selected");
  let budgetText = budgetCard ? budgetCard.innerText.trim() : "Low";
  const user_budget = budgetText.includes("Low")
    ? "low"
    : budgetText.includes("Medium")
    ? "mid"
    : "high";

  try {
    // Solo travelers use /recommend endpoint
    if (roleText === "solo") {
      console.log("Generating solo recommendations...");
      const res = await fetch(`${API_BASE}/recommend`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          user_type: roleText,
          user_interests: user_interests,
          user_budget: user_budget
        })
      });

      if (!res.ok) {
        throw new Error(`API error ${res.status}`);
      }

      const data = await res.json();
      console.log("Received results:", data);
      renderResults(data);
    } else {
      // Group travelers use /generate_group_trip endpoint
      const groupId = localStorage.getItem("currentGroup");
      console.log("Generating group recommendations for:", groupId);
      
      // Ensure user is updated in group before generating
      const currentUserName = localStorage.getItem("currentUserName") || "Anonymous";
      await addCurrentUserToGroup(groupId, currentUserName);

      const res = await fetch(`${API_BASE}/generate_group_trip`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ group_id: groupId })
      });

      if (!res.ok) {
        throw new Error(`API error ${res.status}`);
      }

      const data = await res.json();
      console.log("Received results:", data);
      renderResults(data);
    }
  } catch (err) {
    console.error(err);
    renderResults([], `Request failed: ${err.message}`);
  }
}

/* ---------- RENDER RESULTS INTO HTML ---------- */
function renderResults(results, errorMsg) {
  const container = document.getElementById("results");
  container.innerHTML = `<h2 class='title'>Your Perfect Trips</h2>`;

  if (errorMsg) {
    const err = document.createElement("p");
    err.style.color = "#f88";
    err.textContent = errorMsg;
    container.appendChild(err);
    return;
  }

  if (!results || results.length === 0) {
    const empty = document.createElement("p");
    empty.style.opacity = 0.7;
    empty.textContent = "No results yet. Try adjusting your interests or budget.";
    container.appendChild(empty);
    return;
  }

  results.forEach(place => {
    const card = document.createElement("div");
    card.className = "card result-card";
    card.innerHTML = `
      <h3>${place.place}</h3>
      <p>${place.state}</p>
      <strong>Score: ${place.score}</strong>
    `;
    container.appendChild(card);
  });
}

async function runRecommendationFlow() {
  startLoading();          // show loading animation
  await new Promise(r => setTimeout(r, 2000));  // wait a bit
  await generateRecommendations();               // call backend API
  go("results");                                  // move to results page
}
